version: "3"
services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "8080:80"
    networks:
      - nginx-php
  php:
    image: php8:1.0
    container_name: php
    restart: always
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./www/:/var/www/html/
      - ./php/php8/log/:/var/log/xdebug/
      - ./php/php8/ini/conf.d/:/usr/local/etc/php/conf.d/
    networks:
      - nginx-php
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/log:/var/log/mysql # 映射日志目录，宿主机:容器
      - ./mysql/data:/var/lib/mysql # 映射数据目录，宿主机:容器
      - ./mysql/conf:/etc/mysql/conf.d 
      # 初始化目录挂载，注意此处我只跑了这个挂载，只是为了说明其他配置不应该数据初始化
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=6yAwpcsCHuy*av7ZwiY_
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=dZh8*j6FmDeK9g6Rs79g
      - MYSQL_ROOT_PASSWORD=6FmDeK9g6Rs79g
    networks:
      - nginx-php
  redis:
    image: redis:4
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf:/usr/local/etc/redis:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
    networks:
      - nginx-php

networks:
  nginx-php: